import { useState, useEffect, useRef, useCallback } from "react";
import { AreaChart, Area, ResponsiveContainer, LineChart, Line } from "recharts";
const PAIRS=["BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT"];
const PL={BTCUSDT:"BTC",ETHUSDT:"ETH",BNBUSDT:"BNB",SOLUSDT:"SOL",XRPUSDT:"XRP",DOGEUSDT:"DOGE",ADAUSDT:"ADA",AVAXUSDT:"AVAX"};
const TF_LABEL={"1h":"1 hour","4h":"4 hour","1d":"Daily","1w":"Weekly"};
const calcEMA=(d,p)=>{if(!d.length)return[];const k=2/(p+1);let e=d[0];return d.map(v=>(e=v*k+e*(1-k)));};
const calcSMA=(d,p)=>d.map((_,i)=>{if(i<p-1)return null;let s=0;for(let j=i-p+1;j<=i;j++)s+=d[j];return s/p;});
function calcRSI(c,p=14){if(c.length<p+1)return Array(c.length).fill(50);const r=Array(c.length).fill(50);let ag=0,al=0;for(let i=1;i<=p;i++){const d=c[i]-c[i-1];if(d>0)ag+=d;else al-=d;}ag/=p;al/=p;r[p]=al===0?100:100-100/(1+ag/al);for(let i=p+1;i<c.length;i++){const d=c[i]-c[i-1];ag=(ag*(p-1)+(d>0?d:0))/p;al=(al*(p-1)+(d<0?-d:0))/p;r[i]=al===0?100:100-100/(1+ag/al);}return r;}
function calcBB(c,p=20,m=2){const s=calcSMA(c,p);return s.map((v,i)=>{if(v===null)return{u:null,m:null,l:null};let sm=0;for(let j=i-p+1;j<=i;j++)sm+=(c[j]-v)**2;const sd=Math.sqrt(sm/p);return{u:v+m*sd,m:v,l:v-m*sd,sd};});}
function calcATR(cn,p=14){if(cn.length<2)return Array(cn.length).fill(0);const tr=cn.map((c,i)=>{if(i===0)return c.high-c.low;return Math.max(c.high-c.low,Math.abs(c.high-cn[i-1].close),Math.abs(c.low-cn[i-1].close));});return calcEMA(tr,p);}
function calcADX(cn,p=14){if(cn.length<p*2)return{adx:Array(cn.length).fill(20),pDI:Array(cn.length).fill(25),mDI:Array(cn.length).fill(25)};const pDM=[],mDM=[],tr=[];for(let i=0;i<cn.length;i++){if(i===0){pDM.push(0);mDM.push(0);tr.push(cn[i].high-cn[i].low);continue;}const u=cn[i].high-cn[i-1].high,d=cn[i-1].low-cn[i].low;pDM.push(u>d&&u>0?u:0);mDM.push(d>u&&d>0?d:0);tr.push(Math.max(cn[i].high-cn[i].low,Math.abs(cn[i].high-cn[i-1].close),Math.abs(cn[i].low-cn[i-1].close)));}const a=calcEMA(tr,p),sp=calcEMA(pDM,p),sm=calcEMA(mDM,p);const pD=sp.map((v,i)=>a[i]?v/a[i]*100:0),mD=sm.map((v,i)=>a[i]?v/a[i]*100:0);const dx=pD.map((v,i)=>{const s=v+mD[i];return s?Math.abs(v-mD[i])/s*100:0;});return{adx:calcEMA(dx,p),pDI:pD,mDI:mD};}
function calcCCI(cn,p=20){return cn.map((c,i)=>{if(i<p-1)return 0;const t=[];for(let j=i-p+1;j<=i;j++)t.push((cn[j].high+cn[j].low+cn[j].close)/3);const mn=t.reduce((a,b)=>a+b,0)/p;const md=t.reduce((a,b)=>a+Math.abs(b-mn),0)/p;return md?((c.high+c.low+c.close)/3-mn)/(0.015*md):0;});}

const AG={
  titan:{n:"Titan",i:"▲",c:"#60a5fa",d:"long",tf:"4h",htf:"1d",s:"BB + EMA + RSI Hybrid",tfL:"4h candles, daily confirmation",ind:["BB(20,2)","EMA(50)","RSI(14)"],eL:"4h: price at BB lower + above EMA50 + RSI<40 rising. Daily must be bullish.",eS:"4h: price at BB upper + below EMA50 + RSI>60 falling. Daily bearish.",ex:"TP: BB mid. SL: 1.5×ATR. Hold: hours to days.",edge:"4h structure + daily trend filter. No noise."},
  phantom:{n:"Phantom",i:"▼",c:"#f87171",d:"short",tf:"4h",htf:"1d",s:"Structural Short Seller",tfL:"4h entries, daily confirmation",ind:["EMA(9/21/50)","RSI(14)"],eL:"N/A — shorts only",eS:"4h: EMA9<EMA21<EMA50, RSI<45. Daily: below EMA50.",ex:"TP: 1.5-3×ATR. SL: 1.5×ATR. Hold: days.",edge:"Only shorts macro-confirmed downtrends."},
  reversal:{n:"Reversal",i:"☯",c:"#a78bfa",d:"neutral",tf:"4h",htf:null,s:"Z-Score Mean Reversion",tfL:"4h, 50-period lookback (~8 days)",ind:["SMA(50)","Z-Score"],eL:"Z < -2.0 reverting on 4h. Multi-day deviation.",eS:"Z > 2.0 reverting.",ex:"Exit at z=0. SL: z±3. Time: 30 candles (~5 days).",edge:"4h Z-score = multi-day structure. 80%+ revert rate."},
  shield:{n:"Shield",i:"🛡",c:"#94a3b8",d:"hedge",tf:"4h",htf:null,s:"Portfolio Hedge Overlay",tfL:"Every Conductor cycle",ind:["Net exposure","ATR"],eL:"Inverse of net direction",eS:"—",ex:"Rebalances each cycle.",edge:"Reduces beta 30-50%."},
  razor:{n:"Razor",i:"⚡",c:"#fbbf24",d:"long",tf:"1h",htf:"4h",s:"EMA Cross + RSI Scalp",tfL:"1h entries, 4h trend filter",ind:["EMA(5/13)","RSI(9)"],eL:"1h: EMA5>EMA13 cross + RSI 50-75. 4h: EMA21 trending up.",eS:"1h: EMA5<EMA13 cross. 4h: trending down.",ex:"TP: 1.5×ATR. SL: 1×ATR. Hold: 1-8 hours.",edge:"1h scalps filtered by 4h structure. No counter-trend."},
  grokker:{n:"Grokker",i:"◑",c:"#34d399",d:"contrarian",tf:"4h",htf:"1d",s:"Multi-TF Contrarian Sentiment",tfL:"4h signal, daily confirmation",ind:["RSI(14)","Vol/20avg"],eL:"4h RSI<25 + vol spike + RSI turning. Daily RSI<35.",eS:"4h RSI>75 + vol spike. Daily RSI>65.",ex:"Sentiment flip at RSI 50. SL: 2×ATR. Hold: days.",edge:"Both TFs must show extreme for entry. Very selective."},
  breakout:{n:"Breakout",i:"💥",c:"#fb923c",d:"long",tf:"4h",htf:"1d",s:"Structural Range Escape",tfL:"4h breakout, daily context",ind:["20P High/Low","ATR","Volume"],eL:"4h: close > 20P high + vol>1.3× + ATR expanding. Daily: has room.",eS:"4h: close < 20P low + vol confirms.",ex:"TP: range height. SL: range re-entry. Hold: days-week.",edge:"4h breakout of multi-day range. Volume confirms."},
  fortress:{n:"Fortress",i:"🏰",c:"#7dd3fc",d:"long",tf:"1d",htf:"1w",s:"ADX Macro Trend",tfL:"Daily candles, weekly confirmation",ind:["ADX(14)","+DI/-DI","EMA(50)"],eL:"Daily: ADX>25, +DI>-DI, >EMA50. Weekly: above 20w EMA.",eS:"Daily: ADX>25, -DI>+DI, <EMA50.",ex:"ADX<20 = close. Trail 1.5×ATR. Hold: weeks-months.",edge:"Daily + weekly. Only trades macro confirmed trends."},
  comet:{n:"Comet",i:"☄",c:"#c084fc",d:"long",tf:"1d",htf:null,s:"Smart Daily DCA",tfL:"Daily RSI-adjusted accumulation",ind:["RSI(14)","BB position"],eL:"Daily scheduled buy. RSI<30=1.5×, RSI>70=0.5×.",eS:"N/A — accumulates only",ex:"No exits. Circuit breaker only. Hold: indefinite.",edge:"Daily RSI timing. +8-12% vs naive DCA."},
  pulse:{n:"Pulse",i:"📊",c:"#2dd4bf",d:"neutral",tf:"4h",htf:null,s:"CCI Structural Cycles",tfL:"4h candles — multi-day cycles",ind:["CCI(20)","EMA(50) slope"],eL:"4h CCI crosses above -100, EMA slope positive.",eS:"4h CCI below +100, EMA slope negative.",ex:"CCI opposite extreme. SL: 1.5×ATR. Hold: 1-5 days.",edge:"4h CCI = 3-10 day structural cycles."},
  blitz:{n:"Blitz",i:"🎯",c:"#f472b6",d:"long",tf:"1h",htf:"4h",s:"Structural Momentum",tfL:"1h scan, 4h trend filter",ind:["Vol spike(3×)","ROC(5)","Body ratio"],eL:"1h: Vol>3×, ROC 2-10%, strong body. 4h: EMA21 up.",eS:"N/A — long momentum only",ex:"TP: +5%/+10%. SL: -3%. Hold: hours-2 days.",edge:"1h momentum aligned with 4h structure only."},
};

// Signal functions with higher-TF confirmation
function sigTitan(cn,cl,hCn,hCl){const n=cl.length-1;if(n<50)return{s:"HOLD",c:0,r:"Warming up (need 50× 4h = ~8 days)",ind:{}};const b=calcBB(cl),e50=calcEMA(cl,50),rs=calcRSI(cl),at=calcATR(cn);const bn=b[n];if(!bn?.m)return{s:"HOLD",c:0,r:"BB loading",ind:{}};let hBias="neutral";if(hCl?.length>20){const he=calcEMA(hCl,20),hr=calcRSI(hCl);hBias=hCl[hCl.length-1]>he[he.length-1]&&hr[hr.length-1]>45?"bullish":hCl[hCl.length-1]<he[he.length-1]&&hr[hr.length-1]<55?"bearish":"neutral";}const ind={RSI_4h:rs[n].toFixed(1),EMA50_4h:e50[n].toFixed(2),BB_L:bn.l.toFixed(2),BB_U:bn.u.toFixed(2),ATR:at[n].toFixed(2),Daily:hBias};if(cl[n]<=bn.l&&cl[n]>e50[n]&&rs[n]<40&&rs[n]>rs[n-1]&&hBias!=="bearish")return{s:"LONG",c:hBias==="bullish"?.85:.65,r:`4h: Price ${cl[n].toFixed(2)} at BB lower (${bn.l.toFixed(2)}), above EMA50 (${e50[n].toFixed(2)}). RSI ${rs[n].toFixed(1)} oversold, turning up. Daily: ${hBias}. ${hBias==="bullish"?"Structure aligned.":"Daily neutral — moderate conviction."}`,sl:cl[n]-1.5*at[n],tp:bn.m,ind};if(cl[n]>=bn.u&&cl[n]<e50[n]&&rs[n]>60&&rs[n]<rs[n-1]&&hBias!=="bullish")return{s:"SHORT",c:hBias==="bearish"?.85:.65,r:`4h: Price at BB upper below EMA50. RSI ${rs[n].toFixed(1)} overbought. Daily: ${hBias}.`,sl:cl[n]+1.5*at[n],tp:bn.m,ind};return{s:"HOLD",c:0,r:`4h: Mid-band, RSI ${rs[n].toFixed(1)}. Daily: ${hBias}. No structural setup.`,ind};}
function sigPhantom(cn,cl,hCn,hCl){const n=cl.length-1;if(n<50)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const e9=calcEMA(cl,9),e21=calcEMA(cl,21),e50=calcEMA(cl,50),rs=calcRSI(cl),at=calcATR(cn);let dBear=false;if(hCl?.length>50){const he=calcEMA(hCl,50);dBear=hCl[hCl.length-1]<he[he.length-1];}const ind={RSI_4h:rs[n].toFixed(1),EMA9:e9[n].toFixed(2),EMA21:e21[n].toFixed(2),Daily_Bear:dBear?"Yes":"No"};if(e9[n]<e21[n]&&cl[n]<e50[n]&&rs[n]<45&&dBear){const h3=cn.slice(-3).map(c=>c.high);if(Math.max(...h3)>e21[n]&&cl[n]<e21[n])return{s:"SHORT",c:.8,r:`STRUCTURAL SHORT — 4h failed bounce at EMA21. Bearish stack. DAILY confirms downtrend. RSI ${rs[n].toFixed(1)}.`,sl:e21[n]+at[n],tp:cl[n]-2*at[n],ind};return{s:"SHORT",c:.7,r:`4h bearish + daily downtrend. EMA9<21, below 50. RSI ${rs[n].toFixed(1)}.`,sl:e50[n],tp:cl[n]-1.5*at[n],ind};}if(e9[n]<e21[n]&&!dBear)return{s:"HOLD",c:0,r:`4h bearish but daily NOT confirming. Phantom waits for macro alignment.`,ind};return{s:"HOLD",c:0,r:`No bearish structure. 4h: ${e9[n]>e21[n]?"bull":"mixed"}. Daily: ${dBear?"bear":"not bear"}.`,ind};}
function sigReversal(cn,cl){const n=cl.length-1;if(n<50)return{s:"HOLD",c:0,r:"Warming up (50× 4h = ~8 days)",ind:{}};const sm=calcSMA(cl,50);if(!sm[n])return{s:"HOLD",c:0,r:"SMA loading",ind:{}};let sum=0;for(let i=n-49;i<=n;i++)sum+=(cl[i]-sm[n])**2;const sd=Math.sqrt(sum/50);if(!sd)return{s:"HOLD",c:0,r:"No vol",ind:{}};const z=(cl[n]-sm[n])/sd,pz=n>0?(cl[n-1]-(sm[n-1]||sm[n]))/(sd||1):z;const ind={Z_4h:z.toFixed(2),SMA50:sm[n].toFixed(2),StdDev:sd.toFixed(2)};if(z<-2&&z>pz)return{s:"LONG",c:Math.min(1,Math.abs(z)/3),r:`4h Z-score ${z.toFixed(2)} — ${Math.abs(z).toFixed(1)}σ below 8-day mean (${sm[n].toFixed(2)}). Reverting up. Multi-day structural deviation.`,sl:sm[n]-3*sd,tp:sm[n],ind};if(z>2&&z<pz)return{s:"SHORT",c:Math.min(1,Math.abs(z)/3),r:`4h Z-score ${z.toFixed(2)} — ${z.toFixed(1)}σ above mean. Structural overextension reverting.`,sl:sm[n]+3*sd,tp:sm[n],ind};return{s:"HOLD",c:0,r:`Z ${z.toFixed(2)} within ±2. No structural deviation.`,ind};}
function sigRazor(cn,cl,hCn,hCl){const n=cl.length-1;if(n<20)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const e5=calcEMA(cl,5),e13=calcEMA(cl,13),rs=calcRSI(cl,9),at=calcATR(cn);let hT="neutral";if(hCl?.length>21){const he=calcEMA(hCl,21);hT=he[he.length-1]>he[he.length-2]?"up":"down";}const ind={EMA5_1h:e5[n].toFixed(2),EMA13_1h:e13[n].toFixed(2),RSI9:rs[n].toFixed(1),"4h":hT};if(n>0&&e5[n]>e13[n]&&e5[n-1]<=e13[n-1]&&rs[n]>50&&rs[n]<75&&hT==="up")return{s:"LONG",c:.75,r:`1h bull cross (${e5[n].toFixed(2)}>${e13[n].toFixed(2)}). RSI ${rs[n].toFixed(1)}. 4h structure UP — aligned.`,sl:cl[n]-at[n],tp:cl[n]+1.5*at[n],ind};if(n>0&&e5[n]<e13[n]&&e5[n-1]>=e13[n-1]&&rs[n]<50&&rs[n]>25&&hT==="down")return{s:"SHORT",c:.75,r:`1h bear cross. RSI ${rs[n].toFixed(1)}. 4h DOWN — aligned.`,sl:cl[n]+at[n],tp:cl[n]-1.5*at[n],ind};if(n>0&&e5[n]>e13[n]&&e5[n-1]<=e13[n-1]&&hT!=="up")return{s:"HOLD",c:0,r:`1h bull cross BUT 4h ${hT}. Won't scalp against structure.`,ind};return{s:"HOLD",c:0,r:`No 1h cross. 4h: ${hT}.`,ind};}
function sigBreakout(cn,cl,hCn,hCl){const n=cl.length-1;if(n<25)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const hi=cn.slice(n-20,n).map(c=>c.high),lo=cn.slice(n-20,n).map(c=>c.low);const up=Math.max(...hi),low=Math.min(...lo);const at=calcATR(cn),vol=cn[n].volume,avgV=cn.slice(n-20,n).reduce((a,c)=>a+c.volume,0)/20,vr=(vol/avgV).toFixed(1);let dRoom=true;if(hCl?.length>20){const dhi=Math.max(...hCn.slice(-20).map(c=>c.high));dRoom=cl[n]<dhi*.99;}const ind={"4h_Hi":up.toFixed(2),"4h_Lo":low.toFixed(2),Vol:vr+"×",Daily_Room:dRoom?"Yes":"Resistance"};if(cl[n]>up&&vol>avgV*1.3&&at[n]>at[n-1]&&dRoom)return{s:"LONG",c:.7,r:`4h STRUCTURAL BREAKOUT above ${up.toFixed(2)} (${((up-low)/low*100).toFixed(1)}% range, held ${20*4}h). Vol ${vr}×. Daily has room.`,sl:up-.5*at[n],tp:cl[n]+(up-low),ind};if(cl[n]<low&&vol>avgV*1.3&&at[n]>at[n-1])return{s:"SHORT",c:.7,r:`4h breakdown below ${low.toFixed(2)}. Multi-day support broken. Vol ${vr}×.`,sl:low+.5*at[n],tp:cl[n]-(up-low),ind};return{s:"HOLD",c:0,r:`In range [${low.toFixed(2)}-${up.toFixed(2)}]. Vol ${vr}×. Waiting.`,ind};}
function sigFortress(cn,cl,hCn,hCl){const n=cl.length-1;if(n<30)return{s:"HOLD",c:0,r:"Warming up (need 30 daily = ~1 month)",ind:{}};const{adx:ax,pDI,mDI}=calcADX(cn);const e50=calcEMA(cl,50),at=calcATR(cn);let wk=false;if(hCl?.length>20){const we=calcEMA(hCl,20);wk=hCl[hCl.length-1]>we[we.length-1];}const ind={ADX_D:ax[n].toFixed(1),"+DI":pDI[n].toFixed(1),"-DI":mDI[n].toFixed(1),Weekly:wk?"Bullish":"Not confirmed"};if(ax[n]>25&&pDI[n]>mDI[n]&&cl[n]>e50[n]&&ax[n]>ax[n-1]&&wk)return{s:"LONG",c:Math.min(1,ax[n]/50),r:`MACRO TREND. Daily ADX ${ax[n].toFixed(1)} rising, +DI>${mDI[n].toFixed(1)}. Above EMA50. WEEKLY confirms. Holding weeks.`,sl:cl[n]-2*at[n],tp:cl[n]+3*at[n],ind};if(ax[n]>25&&mDI[n]>pDI[n]&&cl[n]<e50[n]&&ax[n]>ax[n-1])return{s:"SHORT",c:Math.min(1,ax[n]/50),r:`Daily downtrend: ADX ${ax[n].toFixed(1)}, -DI dominates. Below EMA50.`,sl:cl[n]+2*at[n],tp:cl[n]-3*at[n],ind};return{s:"HOLD",c:0,r:`ADX ${ax[n].toFixed(1)} — ${ax[n]<25?"weak":"DI misaligned"}. Weekly: ${wk?"bull":"no"}. Fortress waits.`,ind};}
function sigPulse(cn,cl){const n=cl.length-1;if(n<25)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const cc=calcCCI(cn),e50=calcEMA(cl,50),sl=e50[n]-e50[Math.max(0,n-3)],at=calcATR(cn);const ind={CCI_4h:cc[n].toFixed(0),Slope:sl>0?"Up":"Down"};if(cc[n]>-100&&cc[n-1]<=-100&&sl>0)return{s:"LONG",c:.65,r:`4h CCI above -100 (${cc[n].toFixed(0)} from ${cc[n-1].toFixed(0)}). Multi-day cycle turning bull.`,sl:cl[n]-1.5*at[n],tp:cl[n]+2*at[n],ind};if(cc[n]<100&&cc[n-1]>=100&&sl<0)return{s:"SHORT",c:.65,r:`4h CCI below +100. Cycle turning bear.`,sl:cl[n]+1.5*at[n],tp:cl[n]-2*at[n],ind};return{s:"HOLD",c:0,r:`CCI ${cc[n].toFixed(0)} — no cycle transition.`,ind};}
function sigGrokker(cn,cl,hCn,hCl){const n=cl.length-1;if(n<20)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const rs=calcRSI(cl),vol=cn[n].volume,avgV=cn.slice(Math.max(0,n-20),n).reduce((a,c)=>a+c.volume,0)/20,vr=(vol/avgV).toFixed(1),at=calcATR(cn);let dRSI=50;if(hCl?.length>14){const dr=calcRSI(hCl);dRSI=dr[dr.length-1];}const ind={RSI_4h:rs[n].toFixed(1),RSI_D:dRSI.toFixed(1),Vol:vr+"×"};if(rs[n]<25&&vol>avgV*1.5&&rs[n]>rs[n-1]&&dRSI<35)return{s:"LONG",c:.8,r:`MULTI-TF FEAR — 4h RSI ${rs[n].toFixed(1)} + Daily ${dRSI.toFixed(1)}. Both extreme. Vol ${vr}×. Contrarian buy.`,sl:cl[n]-2*at[n],tp:cl[n]+2.5*at[n],ind};if(rs[n]>75&&vol>avgV*1.5&&rs[n]<rs[n-1]&&dRSI>65)return{s:"SHORT",c:.8,r:`MULTI-TF GREED — 4h ${rs[n].toFixed(1)} + Daily ${dRSI.toFixed(1)}. Fading euphoria.`,sl:cl[n]+2*at[n],tp:cl[n]-2.5*at[n],ind};return{s:"HOLD",c:0,r:`4h RSI ${rs[n].toFixed(1)}, Daily ${dRSI.toFixed(1)}. Need both extreme.`,ind};}
function sigComet(cn,cl,_h,_hc,tick){const n=cl.length-1;if(n<14)return{s:"HOLD",c:0,r:"Warming up",ind:{}};if(tick%10!==0)return{s:"HOLD",c:0,r:`DCA: ${10-tick%10} cycles to next buy`,ind:{}};const rs=calcRSI(cl);let m=1;if(rs[n]<30)m=1.5;else if(rs[n]<40)m=1.25;else if(rs[n]>70)m=.5;else if(rs[n]>60)m=.75;return{s:"LONG",c:.3*m,r:`Daily DCA. RSI ${rs[n].toFixed(1)} → ${m}×. ${m>1?"Oversold — extra.":""}${m<1?"Overbought — less.":""}${m===1?"Normal.":""}`,ind:{RSI_D:rs[n].toFixed(1),Mult:m+"×"}};}
function sigBlitz(cn,cl,hCn,hCl){const n=cl.length-1;if(n<10)return{s:"HOLD",c:0,r:"Warming up",ind:{}};const vol=cn[n].volume,avgV=cn.slice(Math.max(0,n-10),n).reduce((a,c)=>a+c.volume,0)/10,vr=(vol/avgV).toFixed(1);const roc=(cl[n]-cl[Math.max(0,n-5)])/cl[Math.max(0,n-5)]*100;const body=Math.abs(cn[n].close-cn[n].open)/(cn[n].high-cn[n].low||1);let hUp=false;if(hCl?.length>21){const he=calcEMA(hCl,21);hUp=he[he.length-1]>he[he.length-2];}const ind={Vol:vr+"×",ROC:roc.toFixed(2)+"%","4h":hUp?"Up":"Down"};if(vol>avgV*3&&roc>2&&roc<10&&body>.6&&hUp)return{s:"LONG",c:.65,r:`1h momentum + 4h up. Vol ${vr}×, ROC +${roc.toFixed(2)}%. Structural momentum.`,sl:cl[n]*.97,tp:cl[n]*1.05,ind};if(vol>avgV*3&&roc>2&&!hUp)return{s:"HOLD",c:0,r:`1h momentum BUT 4h down. Won't ride against structure.`,ind};return{s:"HOLD",c:0,r:`No momentum. Vol ${vr}×, ROC ${roc.toFixed(2)}%.`,ind};}
const SIG={titan:sigTitan,phantom:sigPhantom,reversal:sigReversal,razor:sigRazor,breakout:sigBreakout,fortress:sigFortress,pulse:sigPulse,grokker:sigGrokker,comet:sigComet,blitz:sigBlitz,shield:()=>({s:"HEDGE",c:.5,r:"Auto-hedge active",ind:{}})};

const CD={aegis:{n:"Aegis",r:"The Guardian",c:"#4A6FA5",rk:"Conservative",db:-.08,ct:.75,ag:["titan","reversal","comet","shield","fortress","pulse"],w:{titan:.15,reversal:.12,comet:.08,shield:.08,fortress:.05,pulse:.05}},atlas:{n:"Atlas",r:"The Strategist",c:"#1B8A6B",rk:"Balanced",db:-.15,ct:.55,ag:["titan","phantom","reversal","grokker","shield","razor"],w:{titan:.20,phantom:.15,reversal:.12,grokker:.10,shield:.10,razor:.08}},apex_c:{n:"Apex",r:"The Opportunist",c:"#E85D26",rk:"Aggressive",db:-.25,ct:.45,ag:["titan","phantom","grokker","breakout","razor","blitz"],w:{titan:.22,phantom:.18,grokker:.15,breakout:.12,razor:.12,blitz:.11}},phantom_edge:{n:"Phantom Edge",r:"The Degen Whisperer",c:"#9B30FF",rk:"Degen",db:-.35,ct:.35,ag:["titan","phantom","grokker","razor","breakout","blitz"],w:{titan:.22,phantom:.20,grokker:.18,razor:.15,breakout:.13,blitz:.12}}};
const REG={bull:{l:"BULLISH",c:"#4ADE80"},bear:{l:"BEARISH",c:"#EF4444"},ranging:{l:"RANGING",c:"#F59E0B"},crash:{l:"CRASH",c:"#EF4444"}};
const fmt=(n,d=2)=>n?.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})??"—";const pct=n=>(n>=0?"+":"")+(n*100).toFixed(2)+"%";

export default function Dashboard(){
  const[allCandles,setAllCandles]=useState({});const[prices,setPrices]=useState({});const[regime,setRegime]=useState("ranging");const[portfolios,setPortfolios]=useState({});const[positions,setPositions]=useState({});const[tradeLog,setTradeLog]=useState([]);const[tick,setTick]=useState(0);const[status,setStatus]=useState("LOADING");const[loadProg,setLoadProg]=useState("");const[selC,setSelC]=useState("atlas");const[view,setView]=useState("dashboard");const[expLog,setExpLog]=useState(null);const startCap=10000;
  const cRef=useRef({});const pRef=useRef({});const posRef=useRef({});const logRef=useRef([]);
  useEffect(()=>{const init={};Object.entries(CD).forEach(([id,c])=>{const as={};c.ag.forEach(a=>{as[a]={pnl:0,trades:0,wins:0,ls:"HOLD",lr:"",op:0};});init[id]={cap:startCap,peak:startCap,agents:as,hist:[{t:Date.now(),v:startCap}],dd:0,cb:false,tc:0};});setPortfolios(init);pRef.current=init;},[]);

  const fetchAll=useCallback(async(init=false)=>{const tfs=new Set();Object.values(AG).forEach(a=>{tfs.add(a.tf);if(a.htf)tfs.add(a.htf);});tfs.add("4h");const data={...cRef.current};const lim=init?100:3;
    for(const tf of tfs){if(!data[tf])data[tf]={};for(const pair of PAIRS){try{if(init)setLoadProg(`${PL[pair]} ${TF_LABEL[tf]||tf}...`);const res=await fetch(`https://api.binance.com/api/v3/klines?symbol=${pair}&interval=${tf}&limit=${lim}`);const raw=await res.json();if(!raw?.length)continue;const candles=raw.map(k=>({time:k[0],open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]}));if(init){data[tf][pair]=candles;}else{if(!data[tf][pair])data[tf][pair]=[];const ex=data[tf][pair];candles.forEach(c=>{const idx=ex.findIndex(e=>e.time===c.time);if(idx>=0)ex[idx]=c;else ex.push(c);});if(ex.length>150)ex.splice(0,ex.length-150);}}catch(e){}await new Promise(r=>setTimeout(r,40));}}
    cRef.current=data;setAllCandles({...data});const pr={};PAIRS.forEach(p=>{const d=data["4h"]?.[p];if(d?.length)pr[p]=d[d.length-1].close;});setPrices(pr);return data;},[]);

  const detectReg=useCallback(data=>{const btc=data?.["4h"]?.BTCUSDT;if(!btc||btc.length<20)return"ranging";const cl=btc.map(c=>c.close);const n=cl.length-1;const e8=calcEMA(cl,8),e21=calcEMA(cl,21),rs=calcRSI(cl);const pc=(cl[n]-cl[Math.max(0,n-12)])/cl[Math.max(0,n-12)];if(pc<-.08)return"crash";if(e8[n]>e21[n]&&rs[n]>50)return"bull";if(e8[n]<e21[n]&&rs[n]<50)return"bear";return"ranging";},[]);

  const runCycle=useCallback((data,t)=>{const r=detectReg(data);setRegime(r);const ports={...pRef.current};const pos={...posRef.current};const nl=[];const em=r==="crash"?.2:r==="bear"?.6:r==="bull"?1.2:1;
    Object.entries(CD).forEach(([cId,cond])=>{if(!ports[cId])return;const port={...ports[cId]};const ags={...port.agents};if(port.cb)return;
      cond.ag.forEach(aId=>{if(!ags[aId])return;const agent=AG[aId];const sigFn=SIG[aId];if(!sigFn)return;const agTF=agent.tf;const agHTF=agent.htf;
        const ps=PAIRS.map(pair=>{const cn=data[agTF]?.[pair];if(!cn?.length||cn.length<20)return{pair,sc:0};const cl=cn.map(c=>c.close);const hCn=agHTF?data[agHTF]?.[pair]:null;const hCl=hCn?.map(c=>c.close);const sig=aId==="comet"?sigFn(cn,cl,hCn,hCl,t):sigFn(cn,cl,hCn,hCl);return{pair,sc:sig.c,sig,cn,cl};}).sort((a,b)=>b.sc-a.sc);
        const best=ps[0];if(!best?.sig)return;const pk=`${cId}_${aId}_${best.pair}`;const ex=pos[pk];const cp=best.cl[best.cl.length-1];const wt=cond.w[aId]||.1;
        ags[aId]={...ags[aId],ls:best.sig.s,lr:best.sig.r,lp:PL[best.pair],ltf:agTF+(agHTF?"+"+agHTF:"")};
        if(aId==="shield")return;
        if(ex){const pp=ex.dir==="long"?(cp-ex.entry)/ex.entry:(ex.entry-cp)/ex.entry;let sc=false,cr="";if(pp<-.025){sc=true;cr=`Stop loss on ${agTF}. ${(pp*100).toFixed(2)}%.`;}if(pp>.05){sc=true;cr=`Take profit on ${agTF}. +${(pp*100).toFixed(2)}%.`;}if(best.sig.s==="HOLD"&&pp>.02){sc=true;cr=`Signal faded on ${agTF}, locking +${(pp*100).toFixed(2)}%.`;}if((ex.dir==="long"&&best.sig.s==="SHORT")||(ex.dir==="short"&&best.sig.s==="LONG")){sc=true;cr=`${agTF} signal reversed.`;}
          if(sc){const rp=pp*ex.size;port.cap+=rp;ags[aId].pnl+=rp;ags[aId].trades++;if(rp>0)ags[aId].wins++;ags[aId].op--;delete pos[pk];nl.push({t:Date.now(),cId,aId,pair:best.pair,act:"CLOSE",dir:ex.dir,pnl:rp,pp,reason:cr,price:cp,entry:ex.entry,size:ex.size,dur:Date.now()-ex.ot,ind:best.sig.ind||{},tf:agTF,htf:agHTF});}return;}
        if(best.sig.s==="HOLD"||best.sig.s==="HEDGE")return;if(best.sig.c<cond.ct)return;
        const ap=Object.keys(pos).filter(k=>k.startsWith(`${cId}_${aId}`)).length;if(ap>=2)return;
        const dir=best.sig.s==="LONG"?"long":"short";const sz=port.cap*wt*em;if(sz<10)return;
        pos[pk]={entry:cp,size:sz,dir,ot:Date.now(),sl:best.sig.sl,tp:best.sig.tp};ags[aId].op=(ags[aId].op||0)+1;port.tc=(port.tc||0)+1;
        nl.push({t:Date.now(),cId,aId,pair:best.pair,act:"OPEN",dir,size:sz,reason:best.sig.r,price:cp,conf:best.sig.c,sl:best.sig.sl,tp:best.sig.tp,ind:best.sig.ind||{},strat:AG[aId]?.s,tf:agTF,htf:agHTF,hold:agTF==="1d"||agTF==="1w"?"weeks":agTF==="4h"?"days":"hours"});
      });
      let up=0;Object.entries(pos).forEach(([k,p])=>{if(!k.startsWith(cId))return;const pts=k.split("_");const pair=pts[2];const agId=pts[1];const agTF=AG[agId]?.tf||"4h";const cp2=data[agTF]?.[pair]?.[data[agTF][pair].length-1]?.close;if(!cp2)return;up+=p.dir==="long"?(cp2-p.entry)/p.entry*p.size:(p.entry-cp2)/p.entry*p.size;});
      const tv=port.cap+up;port.peak=Math.max(port.peak,tv);port.dd=(tv-port.peak)/port.peak;port.cb=port.dd<=cond.db;port.agents=ags;port.hist=[...port.hist.slice(-80),{t:Date.now(),v:tv}];ports[cId]=port;
    });pRef.current=ports;posRef.current=pos;setPortfolios({...ports});setPositions({...pos});
    if(nl.length){logRef.current=[...nl,...logRef.current].slice(0,200);setTradeLog([...logRef.current]);}
  },[detectReg]);

  useEffect(()=>{fetchAll(true).then(d=>{setStatus("LIVE");if(d)runCycle(d,0);});},[fetchAll,runCycle]);
  useEffect(()=>{if(status!=="LIVE")return;const iv=setInterval(async()=>{const data=await fetchAll(false);setTick(t=>{const nt=t+1;runCycle(data,nt);return nt;});},60000);return()=>clearInterval(iv);},[status,fetchAll,runCycle]);

  const rd=REG[regime];const sel=CD[selC];const sp=portfolios[selC];const cLogs=tradeLog.filter(l=>l.cId===selC);
  const T={bg:"#0A0A0B",card:"#111113",border:"#1E1E22",text:"#E8E6E1",sub:"#888",dim:"#555",mute:"#444",green:"#4ADE80",orange:"#F59E0B",red:"#EF4444",blue:"#60a5fa",fontH:"'Bebas Neue',sans-serif",fontB:"'Outfit',sans-serif",fontM:"'JetBrains Mono',monospace"};
  const Badge=({text,color})=>(<span style={{fontSize:10,fontFamily:T.fontM,fontWeight:600,padding:"2px 8px",borderRadius:3,background:color+"20",color,letterSpacing:.5}}>{text}</span>);

  return(<div style={{background:T.bg,color:T.text,minHeight:"100vh",padding:"40px 20px"}}>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Outfit:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet"/>
    <div style={{maxWidth:880,margin:"0 auto"}}>
      <div style={{marginBottom:32}}><div style={{fontFamily:T.fontM,fontSize:10,letterSpacing:4,color:T.dim}}>MULTI-TIMEFRAME SIMULATION · {new Date().toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</div>
        <h1 style={{fontFamily:T.fontH,fontSize:48,fontWeight:700,color:T.text,margin:0,letterSpacing:2}}>AGENT LEAGUE — PAPER TRADING</h1>
        <p style={{fontFamily:T.fontB,fontSize:13,color:T.sub,margin:"8px 0 0",lineHeight:1.6}}>Structural trading on 1h, 4h, daily, and weekly timeframes. Each agent trades its native TF with higher-TF confirmation. Regime on 4h BTC.</p>
      </div>
      {/* TF MAP */}
      <div style={{background:T.card,padding:"14px 18px",marginBottom:24,borderLeft:`3px solid ${T.orange}`}}>
        <div style={{fontFamily:T.fontM,fontSize:9,letterSpacing:2,color:T.dim,marginBottom:8}}>AGENT TIMEFRAME MAP</div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>
          {[{tf:"1h",ag:"Razor ⚡ Blitz 🎯",htf:"↑ 4h filter",col:"#fbbf24"},{tf:"4h",ag:"Titan ▲ Phantom ▼ Reversal ☯ Breakout 💥 Grokker ◑ Pulse 📊 Shield 🛡",htf:"↑ Daily filter",col:"#60a5fa"},{tf:"Daily",ag:"Fortress 🏰 Comet ☄",htf:"↑ Weekly filter",col:"#4ADE80"},{tf:"REGIME",ag:"BTC 4h structure",htf:"EMA(8/21)+RSI",col:rd?.c||"#888"}].map((g,i)=>(
            <div key={i}><div style={{fontFamily:T.fontH,fontSize:18,color:g.col}}>{g.tf}</div><div style={{fontFamily:T.fontB,fontSize:10,color:T.sub,lineHeight:1.4}}>{g.ag}</div><div style={{fontFamily:T.fontM,fontSize:9,color:T.mute}}>{g.htf}</div></div>))}
        </div>
      </div>
      {status==="LOADING"&&<div style={{fontFamily:T.fontM,fontSize:12,color:T.orange,padding:"40px 0",textAlign:"center"}}>{loadProg||"Loading..."}<br/><span style={{fontSize:10,color:T.dim}}>Fetching 1h, 4h, 1d, 1w for 8 pairs (~30s)</span></div>}
      {status==="LIVE"&&(<>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:1,background:T.border,marginBottom:24}}>
          {Object.entries(CD).map(([cId,c])=>{const p=portfolios[cId];if(!p)return null;const tv=p.hist[p.hist.length-1]?.v||startCap;const pp=(tv-startCap)/startCap;
            return(<div key={cId} onClick={()=>setSelC(cId)} style={{background:T.bg,padding:"16px 20px",cursor:"pointer",borderBottom:selC===cId?`2px solid ${c.c}`:"2px solid transparent"}}>
              <div style={{fontFamily:T.fontM,fontSize:10,letterSpacing:2,color:T.dim}}>{c.n}</div><div style={{fontFamily:T.fontH,fontSize:32,color:T.text}}>{pct(pp)}</div>
              <div style={{fontFamily:T.fontM,fontSize:10,color:T.mute}}>${fmt(tv,0)} · {p.tc||0} trades · DD {(p.dd*100).toFixed(1)}%</div>
              {p.hist.length>3&&<div style={{height:24,marginTop:8,marginLeft:-4,marginRight:-4}}><ResponsiveContainer width="100%" height="100%"><LineChart data={p.hist.slice(-30)}><Line type="monotone" dataKey="v" stroke={c.c} strokeWidth={1.2} dot={false}/></LineChart></ResponsiveContainer></div>}
            </div>);})}
        </div>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}>
          <div style={{display:"flex",gap:12,alignItems:"center"}}><Badge text={rd?.l||"—"} color={rd?.c||"#888"}/><span style={{fontFamily:T.fontM,fontSize:10,color:T.mute}}>4h BTC · Tick {tick} · 60s</span><span style={{width:6,height:6,borderRadius:"50%",background:T.green,boxShadow:`0 0 6px ${T.green}`}}/></div>
          <div style={{display:"flex",gap:8}}>{Object.entries(prices).slice(0,5).map(([p,pr])=>(<span key={p} style={{fontFamily:T.fontM,fontSize:10,color:T.sub}}>{PL[p]} <span style={{color:T.text}}>${fmt(pr,pr<1?4:pr<100?2:0)}</span></span>))}</div>
        </div>
        <div style={{display:"flex",gap:0,marginBottom:24,borderBottom:`1px solid ${T.border}`}}>
          {[{id:"dashboard",l:"Dashboard"},{id:"logbook",l:`Order Log (${cLogs.length})`},{id:"strategies",l:"Strategies"}].map(v=>(<button key={v.id} onClick={()=>{setView(v.id);setExpLog(null);}} style={{fontFamily:T.fontM,fontSize:11,letterSpacing:1,padding:"10px 20px",background:"transparent",color:view===v.id?T.text:T.dim,cursor:"pointer",border:"none",borderBottom:view===v.id?`2px solid ${sel.c}`:"2px solid transparent"}}>{v.l}</button>))}
        </div>
        {/* DASHBOARD */}
        {view==="dashboard"&&sp&&(<>
          <div style={{borderLeft:`3px solid ${sel.c}`,paddingLeft:16,marginBottom:28}}><h2 style={{fontFamily:T.fontH,fontSize:24,color:T.text,margin:0}}>{sel.n.toUpperCase()} AGENTS</h2><div style={{fontFamily:T.fontM,fontSize:10,color:T.dim}}>{sel.ag.length} agents · Multi-TF · {sel.rk}</div></div>
          <div style={{display:"flex",flexDirection:"column",gap:2,marginBottom:28}}>
            {sel.ag.map(aId=>{const ag=AG[aId];const st=sp.agents?.[aId];if(!ag||!st)return null;const act=st.ls!=="HOLD"&&!st.ls?.includes("Warm");const wr=st.trades>0?(st.wins/st.trades*100).toFixed(0):"—";
              return(<div key={aId} style={{display:"grid",gridTemplateColumns:"24px 1fr 60px 80px 55px",gap:8,padding:"10px 14px",background:T.card,borderLeft:`3px solid ${act?ag.c:T.border}`,alignItems:"center"}}>
                <span style={{fontSize:14}}>{ag.i}</span>
                <div><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontFamily:T.fontB,fontSize:13,fontWeight:500,color:T.text}}>{ag.n}</span>{st.ls!=="HOLD"?<Badge text={st.ls} color={st.ls==="LONG"?T.green:st.ls==="SHORT"?T.red:T.orange}/>:<span style={{fontFamily:T.fontM,fontSize:10,color:T.mute}}>HOLD</span>}<span style={{fontFamily:T.fontM,fontSize:9,padding:"1px 6px",background:T.border,borderRadius:2,color:T.dim}}>{ag.tf}{ag.htf?"+"+ag.htf:""}</span>{st.lp&&<span style={{fontFamily:T.fontM,fontSize:9,color:T.mute}}>{st.lp}</span>}</div>
                  <div style={{fontFamily:T.fontB,fontSize:11,color:T.sub,marginTop:2,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",maxWidth:420}}>{st.lr}</div></div>
                <div style={{textAlign:"right"}}><div style={{fontFamily:T.fontM,fontSize:12,fontWeight:600,color:st.pnl>=0?T.green:T.red}}>{st.pnl>=0?"+":""}{fmt(st.pnl,0)}</div><div style={{fontFamily:T.fontM,fontSize:9,color:T.mute}}>{st.trades}t</div></div>
                <div style={{textAlign:"right",fontFamily:T.fontM,fontSize:10,color:T.sub}}>{wr}% WR</div>
                <div style={{textAlign:"right",fontFamily:T.fontM,fontSize:9,color:T.dim}}>{ag.tf==="1d"||ag.tf==="1w"?"weeks":ag.tf==="4h"?"days":"hours"}</div>
              </div>);})}
          </div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:28}}>
            <div><div style={{borderLeft:`3px solid ${sel.c}`,paddingLeft:16,marginBottom:12}}><h2 style={{fontFamily:T.fontH,fontSize:24,color:T.text,margin:0}}>EQUITY</h2></div>
              <div style={{background:T.card,padding:16}}>{sp.hist.length>3&&<div style={{height:100}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={sp.hist}><defs><linearGradient id="eg" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={sel.c} stopOpacity={.3}/><stop offset="100%" stopColor={sel.c} stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="v" stroke={sel.c} fill="url(#eg)" strokeWidth={1.5} dot={false}/></AreaChart></ResponsiveContainer></div>}
                <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:12}}>{[{l:"Capital",v:`$${fmt(sp.hist[sp.hist.length-1]?.v||startCap,0)}`},{l:"DD",v:`${(sp.dd*100).toFixed(2)}%`},{l:"Trades",v:sp.tc||0},{l:"Breaker",v:`${(sel.db*100).toFixed(0)}%`}].map((s,i)=>(<div key={i} style={{textAlign:"center"}}><div style={{fontFamily:T.fontH,fontSize:20,color:T.text}}>{s.v}</div><div style={{fontFamily:T.fontM,fontSize:9,color:T.dim}}>{s.l}</div></div>))}</div></div></div>
            <div><div style={{borderLeft:`3px solid ${T.border}`,paddingLeft:16,marginBottom:12}}><h2 style={{fontFamily:T.fontH,fontSize:24,color:T.text,margin:0}}>POSITIONS</h2></div>
              <div style={{background:T.card,padding:16}}>{Object.entries(positions).filter(([k])=>k.startsWith(selC)).length===0?<div style={{fontFamily:T.fontB,fontSize:12,color:T.dim,padding:"16px 0",textAlign:"center"}}>No open positions</div>:Object.entries(positions).filter(([k])=>k.startsWith(selC)).map(([k,p])=>{const pts=k.split("_");const pair=pts[2];const agId=pts[1];const agTF=AG[agId]?.tf||"4h";const cp2=allCandles[agTF]?.[pair]?.[allCandles[agTF][pair].length-1]?.close;const pp2=cp2?(p.dir==="long"?(cp2-p.entry)/p.entry:(p.entry-cp2)/p.entry):0;
                return(<div key={k} style={{display:"grid",gridTemplateColumns:"70px 40px 35px 1fr 50px",gap:6,padding:"8px 0",borderBottom:`1px solid ${T.border}`,alignItems:"center"}}><span style={{fontFamily:T.fontB,fontSize:11,color:AG[agId]?.c}}>{AG[agId]?.i} {AG[agId]?.n}</span><Badge text={p.dir.toUpperCase()} color={p.dir==="long"?T.green:T.red}/><span style={{fontFamily:T.fontM,fontSize:9,color:T.dim}}>{agTF}</span><span style={{fontFamily:T.fontM,fontSize:10,color:T.sub}}>{PL[pair]} @ {fmt(p.entry,p.entry<1?4:2)}</span><span style={{textAlign:"right",fontFamily:T.fontM,fontSize:11,fontWeight:600,color:pp2>=0?T.green:T.red}}>{(pp2*100).toFixed(2)}%</span></div>);})}</div></div>
          </div>
          <div style={{borderLeft:`3px solid ${T.border}`,paddingLeft:16,marginBottom:12,display:"flex",justifyContent:"space-between"}}><h2 style={{fontFamily:T.fontH,fontSize:24,color:T.text,margin:0}}>RECENT</h2><button onClick={()=>setView("logbook")} style={{fontFamily:T.fontM,fontSize:10,color:sel.c,background:"transparent",border:"none",cursor:"pointer"}}>Full log →</button></div>
          {cLogs.slice(0,5).map((l,i)=>{const ag=AG[l.aId];return(<div key={i} style={{display:"grid",gridTemplateColumns:"80px 50px 35px 30px 40px 1fr 60px",gap:6,padding:"8px 14px",background:i===0?T.card:"transparent",borderLeft:`3px solid ${l.act==="OPEN"?T.blue:"#a855f7"}`,alignItems:"center",fontFamily:T.fontM,fontSize:10}}><span style={{color:ag?.c}}>{ag?.i} {ag?.n}</span><Badge text={l.act} color={l.act==="OPEN"?T.blue:"#a855f7"}/><span style={{color:l.dir==="long"?T.green:T.red}}>{l.dir?.toUpperCase()}</span><span style={{color:T.orange}}>{l.tf}</span><span style={{color:T.sub}}>{PL[l.pair]}</span><span style={{color:T.dim,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{l.reason?.slice(0,50)}</span><span style={{textAlign:"right",fontWeight:600,color:l.pnl!=null?(l.pnl>=0?T.green:T.red):T.sub}}>{l.pnl!=null?`${l.pnl>=0?"+":""}$${Math.abs(l.pnl).toFixed(0)}`:`$${l.size?.toFixed(0)||""}`}</span></div>);})}
        </>)}
        {/* LOGBOOK */}
        {view==="logbook"&&(<div><div style={{borderLeft:`3px solid ${sel.c}`,paddingLeft:16,marginBottom:20}}><h2 style={{fontFamily:T.fontH,fontSize:24,color:T.text,margin:0}}>{sel.n.toUpperCase()} ORDER LOG</h2><div style={{fontFamily:T.fontB,fontSize:13,color:T.sub,marginTop:4}}>Multi-timeframe trades with HTF confirmation. Click to expand.</div></div>
          {cLogs.length===0?<div style={{fontFamily:T.fontB,fontSize:13,color:T.dim,padding:"40px 0",textAlign:"center",background:T.card}}>No trades yet. Structural signals on 4h/1d/1w are less frequent but higher quality. Patience.</div>
          :cLogs.map((l,i)=>{const ag=AG[l.aId];const isE=expLog===i;return(<div key={i} style={{marginBottom:1}}><div onClick={()=>setExpLog(isE?null:i)} style={{display:"grid",gridTemplateColumns:"20px 70px 50px 35px 30px 40px 1fr 60px 45px",gap:4,padding:"10px 14px",background:isE?"#161618":T.card,borderLeft:`3px solid ${l.act==="OPEN"?T.blue:"#a855f7"}`,cursor:"pointer",alignItems:"center"}}><span style={{fontSize:12}}>{ag?.i}</span><span style={{fontFamily:T.fontB,fontSize:12,color:ag?.c}}>{ag?.n}</span><Badge text={l.act} color={l.act==="OPEN"?T.blue:"#a855f7"}/><span style={{fontFamily:T.fontM,fontSize:10,color:l.dir==="long"?T.green:T.red,fontWeight:600}}>{l.dir?.toUpperCase()}</span><span style={{fontFamily:T.fontM,fontSize:9,color:T.orange}}>{l.tf}</span><span style={{fontFamily:T.fontM,fontSize:10,color:T.sub}}>{PL[l.pair]}</span><span style={{fontFamily:T.fontB,fontSize:11,color:T.dim,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{l.reason?.slice(0,40)}...</span><span style={{textAlign:"right",fontFamily:T.fontM,fontSize:11,fontWeight:600,color:l.pnl!=null?(l.pnl>=0?T.green:T.red):T.blue}}>{l.pnl!=null?`${l.pnl>=0?"+":""}$${Math.abs(l.pnl).toFixed(2)}`:`$${l.size?.toFixed(0)}`}</span><span style={{textAlign:"right",fontFamily:T.fontM,fontSize:9,color:T.mute}}>{new Date(l.t).toLocaleTimeString("en-US",{hour12:false})}</span></div>
            {isE&&(<div style={{padding:"16px 20px 16px 37px",background:"#0D0D0E",borderLeft:`3px solid ${T.border}`}}>
              <div style={{marginBottom:8,display:"flex",gap:12,alignItems:"center"}}>{l.strat&&<><span style={{fontFamily:T.fontM,fontSize:9,color:T.dim}}>STRATEGY</span><span style={{fontFamily:T.fontB,fontSize:13,color:ag?.c}}>{l.strat}</span></>}<span style={{fontFamily:T.fontM,fontSize:10,padding:"2px 8px",background:T.orange+"20",color:T.orange,borderRadius:2}}>{l.tf}{l.htf?" + "+l.htf:""}</span>{l.hold&&<span style={{fontFamily:T.fontM,fontSize:10,color:T.dim}}>Hold: {l.hold}</span>}</div>
              <div style={{fontFamily:T.fontB,fontSize:13,color:"#aaa",lineHeight:1.8,marginBottom:12}}>{l.reason}</div>
              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:12}}>{[{l:"Entry",v:`$${fmt(l.price,l.price<1?4:2)}`},l.sl&&{l:"SL",v:`$${fmt(l.sl,l.sl<1?4:2)}`,c:T.red},l.tp&&{l:"TP",v:`$${fmt(l.tp,l.tp<1?4:2)}`,c:T.green},l.size&&{l:"Size",v:`$${fmt(l.size,0)}`},l.conf!=null&&{l:"Conf",v:`${(l.conf*100).toFixed(0)}%`},l.pnl!=null&&{l:"P&L",v:`${l.pnl>=0?"+":""}$${fmt(l.pnl,2)}`,c:l.pnl>=0?T.green:T.red},l.dur&&{l:"Duration",v:`${Math.floor(l.dur/3600000)}h ${Math.floor((l.dur%3600000)/60000)}m`}].filter(Boolean).map((s,j)=>(<div key={j}><div style={{fontFamily:T.fontM,fontSize:9,color:T.dim}}>{s.l}</div><div style={{fontFamily:T.fontM,fontSize:13,color:s.c||T.text}}>{s.v}</div></div>))}</div>
              {l.ind&&Object.keys(l.ind).length>0&&<div><div style={{fontFamily:T.fontM,fontSize:9,color:T.dim,letterSpacing:2,marginBottom:6}}>INDICATORS</div><div style={{display:"flex",flexWrap:"wrap",gap:4}}>{Object.entries(l.ind).map(([k,v])=>(<span key={k} style={{fontFamily:T.fontM,fontSize:10,padding:"3px 10px",background:T.card,border:`1px solid ${T.border}`,borderRadius:2}}><span style={{color:T.dim}}>{k}: </span><span style={{color:T.text}}>{v}</span></span>))}</div></div>}
            </div>)}</div>);})}
        </div>)}
        {/* STRATEGIES */}
        {view==="strategies"&&(<div><div style={{borderLeft:`3px solid ${sel.c}`,paddingLeft:16,marginBottom:24}}><h2 style={{fontFamily:T.fontH,fontSize:24,color:T.text,margin:0}}>{sel.n.toUpperCase()} STRATEGIES</h2></div>
          {sel.ag.map(aId=>{const ag=AG[aId];if(!ag)return null;return(<div key={aId} style={{background:T.card,borderLeft:`3px solid ${ag.c}`,padding:"20px 24px",marginBottom:8}}>
            <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><span style={{fontSize:20}}>{ag.i}</span><div><div style={{fontFamily:T.fontH,fontSize:20,color:ag.c}}>{ag.n.toUpperCase()}</div><div style={{fontFamily:T.fontB,fontSize:12,color:T.sub}}>{ag.s}</div></div><div style={{flex:1}}/><div style={{display:"flex",gap:4}}><span style={{fontFamily:T.fontM,fontSize:10,padding:"3px 8px",background:T.orange+"20",color:T.orange,borderRadius:2}}>{ag.tf}</span>{ag.htf&&<span style={{fontFamily:T.fontM,fontSize:10,padding:"3px 8px",background:T.blue+"20",color:T.blue,borderRadius:2}}>+{ag.htf}</span>}</div></div>
            <div style={{fontFamily:T.fontB,fontSize:12,color:T.sub,marginBottom:12,fontStyle:"italic"}}>{ag.tfL}</div>
            <div style={{display:"flex",flexWrap:"wrap",gap:4,marginBottom:16}}>{ag.ind.map((ind,j)=>(<span key={j} style={{fontFamily:T.fontM,fontSize:10,padding:"3px 10px",background:`${ag.c}10`,border:`1px solid ${ag.c}30`,borderRadius:2,color:ag.c}}>{ind}</span>))}</div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20,fontFamily:T.fontB,fontSize:12,lineHeight:1.7}}>
              <div><div style={{fontFamily:T.fontM,fontSize:9,letterSpacing:2,color:T.dim,marginBottom:4}}>ENTRY LONG</div><div style={{color:"#aaa",marginBottom:12}}>{ag.eL}</div><div style={{fontFamily:T.fontM,fontSize:9,letterSpacing:2,color:T.dim,marginBottom:4}}>ENTRY SHORT</div><div style={{color:"#aaa"}}>{ag.eS}</div></div>
              <div><div style={{fontFamily:T.fontM,fontSize:9,letterSpacing:2,color:T.dim,marginBottom:4}}>EXIT</div><div style={{color:"#aaa",marginBottom:12}}>{ag.ex}</div><div style={{fontFamily:T.fontM,fontSize:9,letterSpacing:2,color:T.dim,marginBottom:4}}>EDGE</div><div style={{color:T.text,fontStyle:"italic"}}>{ag.edge}</div></div>
            </div></div>);})}
        </div>)}
        <div style={{display:"grid",gridTemplateColumns:"repeat(8,1fr)",gap:1,background:T.border,marginTop:28}}>{PAIRS.map(p=>(<div key={p} style={{background:T.bg,padding:"8px",textAlign:"center"}}><div style={{fontFamily:T.fontM,fontSize:9,color:T.dim}}>{PL[p]}</div><div style={{fontFamily:T.fontM,fontSize:11,fontWeight:600,color:T.text}}>{prices[p]?fmt(prices[p],prices[p]<1?4:prices[p]<100?2:0):"—"}</div></div>))}</div>
        <div style={{fontFamily:T.fontM,fontSize:9,color:T.mute,textAlign:"center",marginTop:20,letterSpacing:2}}>MULTI-TIMEFRAME PAPER TRADING · 1h / 4h / 1D / 1W · STRUCTURAL SIGNALS · NOT FINANCIAL ADVICE</div>
      </>)}
    </div>
  </div>);
}

